export const apiBase = 'http://localhost:5000';

export const authConstants = {
  AUTH_LOGOUT_FAILURE: 'AUTH_LOGOUT_FAILURE',
  AUTH_LOGOUT_REQUEST: 'AUTH_LOGOUT_REQUEST',
  AUTH_LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',

  AUTH_SIGN_IN_FAILURE: 'AUTH_SIGN_IN_FAILURE',
  AUTH_SIGN_IN_REQUEST: 'AUTH_SIGN_IN_REQUEST',
  AUTH_SIGN_IN_SUCCESS: 'AUTH_SIGN_IN_SUCCESS',

  AUTH_SIGN_UP_REQUEST: 'AUTH_SIGN_UP_REQUEST',
  AUTH_SIGN_UP_SUCCESS: 'AUTH_SIGN_UP_SUCCESS',
  AUTH_SIGN_UP_FAILURE: 'AUTH_SIGN_UP_FAILURE',

  COOKIE_KEY: 'auth_user'
};

export const articleConstants = {
  ARTICLE_GETLIST_FAILURE: 'ARTICLE_GETLIST_FAILURE',
  ARTICLE_GETLIST_REQUEST: 'ARTICLE_GETLIST_REQUEST',
  ARTICLE_GETLIST_SUCCESS: 'ARTICLE_GETLIST_SUCCESS',

  ARTICLE_GET_REQUEST: 'ARTICLE_GET_REQUEST',
  ARTICLE_GET_SUCCESS: 'ARTICLE_GET_SUCCESS',
  ARTICLE_GET_FAILURE: 'ARTICLE_GET_FAILURE',

  ARTICLE_ADD_REQUEST: 'ARTICLE_ADD_REQUEST',
  ARTICLE_ADD_SUCCESS: 'ARTICLE_ADD_SUCCESS',
  ARTICLE_ADD_FAILURE: 'ARTICLE_ADD_FAILURE',

  ARTICLE_DELETE_REQUEST: 'ARTICLE_DELETE_REQUEST',
  ARTICLE_DELETE_SUCCESS: 'ARTICLE_DELETE_SUCCESS',
  ARTICLE_DELETE_FAILURE: 'ARTICLE_DELETE_FAILURE',

  ARTICLE_END_DELETE: 'ARTICLE_END_DELETE'
};

export const commentConstants = {
  COMMENT_GETLIST_REQUEST: 'COMMENT_GETLIST_REQUEST',
  COMMENT_GETLIST_SUCCESS: 'COMMENT_GETLIST_SUCCESS',
  COMMENT_GETLIST_FAILURE: 'COMMENT_GETLIST_FAILURE',

  COMMENT_ADD_REQUEST: 'COMMENT_ADD_REQUEST',
  COMMENT_ADD_SUCCESS: 'COMMENT_ADD_SUCCESS',
  COMMENT_ADD_FAILURE: 'COMMENT_ADD_FAILURE',

  COMMENT_CHANGE_PARENT: 'COMMENT_CHANGE_PARENT'
};

export const keyWordConstants = {
  KEYWORD_GETLIST_REQUEST: 'KEYWORD_GETLIST_REQUEST',
  KEYWORD_GETLIST_SUCCESS: 'KEYWORD_GETLIST_SUCCESS',
  KEYWORD_GETLIST_FAILURE: 'KEYWORD_GETLIST_FAILURE',

  KEYWORD_ADD_REQUEST: 'KEYWORD_ADD_REQUEST',
  KEYWORD_ADD_SUCCESS: 'KEYWORD_ADD_SUCCESS',
  KEYWORD_ADD_FAILURE: 'KEYWORD_ADD_FAILURE'
};

export const headerConstants = {
  HEADER_SET_ACTIVE_ITEM_REQUEST: 'HEADER_SET_ACTIVE_ITEM_REQUEST',
  HEADER_SET_ACTIVE_ITEM_SUCCESS: 'HEADER_SET_ACTIVE_ITEM_SUCCESS',
  HEADER_SET_ACTIVE_ITEM_FAILURE: 'HEADER_SET_ACTIVE_ITEM_FAILURE'
};

export const modalConstants = {
  SHOW_MODAL: 'SHOW_MODAL',
  HIDE_MODAL: 'HIDE_MODAL'
};
